dist: trusty
language: cpp
if: (branch =~ ^(dev|master|test_ci)$) || (branch =~ ^feat\/.*$) || (tag =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$)
services:
  - docker
env:
  - BUILD_TYPE=release TARGET_ARCH=amd64
  - BUILD_TYPE=debug TARGET_ARCH=amd64
  - BUILD_TYPE=release TARGET_ARCH=i386
  - BUILD_TYPE=debug TARGET_ARCH=i386
os:
  - osx
  - linux
osx_image: xcode10.3
matrix:
  include:
    - os: linux
      env:
        - BUILD_TYPE=release TARGET_ARCH=arm
    - os: linux
      env:
        - BUILD_TYPE=debug TARGET_ARCH=arm
    - os: linux
      env:
        - BUILD_TYPE=release TARGET_ARCH=arm64
    - os: linux
      env:
        - BUILD_TYPE=debug TARGET_ARCH=arm64
    - os: linux
      env:
        - BUILD_TYPE=release TARGET_ARCH=mips
    - os: linux
      env:
        - BUILD_TYPE=debug TARGET_ARCH=mips
    - os: linux
      env:
        - BUILD_TYPE=release TARGET_ARCH=mips64
    - os: linux
      env:
        - BUILD_TYPE=debug TARGET_ARCH=mips64
cache: ccache
addons:
  apt:
    packages:
     - ccache
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.4.0;
      rvm --default use 2.4.0;
      ruby -v;
      brew update;
    fi
install:
  - git submodule init
  - git submodule update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
      brew install xz;
    fi
script:
  - echo "${TARGET_ARCH}"
  - ./.travis/build.sh
  - ./.travis/release.sh
before_deploy:
  - export GIT_COMMIT_SHORTCUTS=$(git log --format=%h -1)
  - export GIT_COMMIT_TIME=$(git show -s --format="%cd" --date=format:%Y%m%d%H%M%S $TRAVIS_BRANCH)
  - if [[ -z $TRAVIS_TAG ]]; then
      export TRAVIS_TAG="$GIT_COMMIT_TIME-$GIT_COMMIT_SHORTCUTS";
      if [ $(git tag --list | egrep "^$TRAVIS_TAG$") ]; then
        echo "tag $TRAVIS_TAG existed";
      else
        git config --local user.name "richardo2016";
        git config --local user.email "richardo2016@gmail.com";
        git tag "$TRAVIS_TAG" "$GIT_COMMIT_SHORTCUTS";
        echo "created new tag $TRAVIS_TAG";
      fi
    fi
  - echo "$TRAVIS_TAG" "$GIT_COMMIT_SHORTCUTS"
deploy:
  - provider: releases
    name: ${TRAVIS_TAG}
    body: Automated release from Travis CI on ${TRAVIS_BRANCH} (${TRAVIS_COMMIT})
    tag_name: ${TRAVIS_TAG}
    # This is important as the tag doesn't exist in the remote repo yet. GitHub needs to know where to create it.
    # If we don't specify the target explicitly, github will create the tag at
    # the tip of master, which is obviously incorrect.
    # **NOTICE**: it must be full commit hash!
    target_commitish: ${TRAVIS_COMMIT}
    api_key:
      secure: FbRQUq20NURkts8bswu1lkRCLCBlPZLZUoEYdRw5hMMvKqdUNJqlEKpwowvOelsKDcrgdUkgLrFMGlCIu38shZomx/dg+5N9PEnPQS7iNS9tT2I3IjNAMoPCtpkXaLz9zqo17d1jajNZs2t6WNyKYTWq+8oENXa6MbgWSt/odRhPLdl00S9iO4hUukOKI13gf1iW3FsYTYrkHQ3mMG/a4HkOC57RyEXoyXGpqDi/fHQGof55AMONCVTG3Tts2IZgUOf0GJMCEzAur970m6x3cLa0rX0XQ0Ykwi4NwDVubhcO6+pgFeu1WCwjZCLsX6qD1usl5s3Ny3MloO2iSbM+QNBdiyrX499odLzIgnwfL5n5AMkYGgr4SJvOEpc+I8OZOW2aLTa1I6xtIWBdJad6tP2+EXZ6LSX6DJgFMkZ5JhRhVLol0TGV+2K2RhUoF/tjDBBwYqCeEoeH6EgOM5Aq1sVsl+e/SenRynSv6n1aO6IfkyVcVG2KssfuN3nwVcw+QIn9HqFJ4PoBGZR5y4lrzsE+F6lP1y5DLyW0gdxKQaRnG9xixCEuh7C6DWs4p9w9jJalx1nt+J1JQ6keJ+F7tWohew1ZWtNzf4kapinpPYR3SEkNCAhCq9S7vYFT/GZAv2tWk3axYkWyZ8nF3Gx6EK4D6n3EVqGLIfFfJrYK1R8=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    prerelease: true
    skip_cleanup: true
    overwrite: true
    on:
      repo: fibjs/fibjs_vender
      all_branches: true
  - provider: releases
    name: dev
    body: Automated release from Travis CI on dev (${TRAVIS_COMMIT})
    api_key:
      secure: FbRQUq20NURkts8bswu1lkRCLCBlPZLZUoEYdRw5hMMvKqdUNJqlEKpwowvOelsKDcrgdUkgLrFMGlCIu38shZomx/dg+5N9PEnPQS7iNS9tT2I3IjNAMoPCtpkXaLz9zqo17d1jajNZs2t6WNyKYTWq+8oENXa6MbgWSt/odRhPLdl00S9iO4hUukOKI13gf1iW3FsYTYrkHQ3mMG/a4HkOC57RyEXoyXGpqDi/fHQGof55AMONCVTG3Tts2IZgUOf0GJMCEzAur970m6x3cLa0rX0XQ0Ykwi4NwDVubhcO6+pgFeu1WCwjZCLsX6qD1usl5s3Ny3MloO2iSbM+QNBdiyrX499odLzIgnwfL5n5AMkYGgr4SJvOEpc+I8OZOW2aLTa1I6xtIWBdJad6tP2+EXZ6LSX6DJgFMkZ5JhRhVLol0TGV+2K2RhUoF/tjDBBwYqCeEoeH6EgOM5Aq1sVsl+e/SenRynSv6n1aO6IfkyVcVG2KssfuN3nwVcw+QIn9HqFJ4PoBGZR5y4lrzsE+F6lP1y5DLyW0gdxKQaRnG9xixCEuh7C6DWs4p9w9jJalx1nt+J1JQ6keJ+F7tWohew1ZWtNzf4kapinpPYR3SEkNCAhCq9S7vYFT/GZAv2tWk3axYkWyZ8nF3Gx6EK4D6n3EVqGLIfFfJrYK1R8=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    prerelease: true
    skip_cleanup: true
    overwrite: true
    on:
      repo: fibjs/fibjs_vender
      branch: dev